apiVersion: apps/v1
kind: Deployment
metadata:
  name: queryservice
spec:
  selector:
    matchLabels:
      app: queryservice
  replicas: 2
  template:
    metadata:
      annotations:
        traffic.sidecar.istio.io/excludeOutboundIPRanges: 0.0.0.0/0
      labels:
        app: queryservice
        tier: frontend
        version: v1
    spec:
      containers:
      - name: queryservice
        image: gcr.io/_PROJECT_ID/queryservice:TAG_NAME
        args: ["--spring.redis.host=REDIS_HOST",
        "--spring.application.name=queryservice",
        "--grpc.server.name=cacheservice",
        "--grpc.server.port=6565",
        "--server.port=8080"]
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 60
          successThreshold: 1
          timeoutSeconds: 10        
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: server
        - containerPort: 8081
          name: management
        env:  
        - name: PROJECT_ID
          value: _PROJECT_ID
        - name: GOOGLE_CLOUD_PROJECT
          value: _PROJECT_ID
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /etc/app-gac/app-gac.json
        volumeMounts:
          - name: app-gac-vol
            mountPath: "/etc/app-gac"
            readOnly: true
      volumes:
      - name: app-gac-vol
        secret:
          secretName: app-gac
---
apiVersion: v1
kind: Service
metadata:
  name: queryservice
  labels:
    app: queryservice
    tier: frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: queryservice
    tier: frontend